baseURL = 'https://zoelocke.github.io/108-moves/'
languageCode = 'en-gb'
title = '108 Moves'

[pagination]
  pagerSize = 10

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'

[params]
  description = 'A step-by-step guide to the simplified versions of the 108 moves of Tai Chi as practised by the Caerphilly beginner class of Tai Chi Evolutions.'
  favicon = 'favicon.svg'
  login_password = 'TCE2026'
  recaptcha_site_key = ''  # Register at https://www.google.com/recaptcha/admin/create and paste your v2 site key here
  show_steps = false

[taxonomies]
  category = 'categories'
  tag = 'tags'

[menu]
  [[menu.main]]
    name = 'Home'
    pageRef = '/'
    weight = 1
  [[menu.main]]
    name = 'Tutorial'
    pageRef = '/tutorial'
    weight = 2


[outputs]
  home = ['HTML', 'RSS', 'JSON']
  page = ['HTML']
  section = ['HTML', 'RSS']